### ISSUE TITLE
Feedback for “Obsidian Plugin”

### ISSUE THREAD

**Issue by jatawei** [aidenlx/obsidian-zotero-docs#1]
thanks for the plugin. But i couldn't find the note in the obsidian template zotero item details. Is it going to update or it is not the key of this plugin? Because lots of notes are written in the "note" and i really want to import them into obsidian. Or it's just because i miss something? Thanks for reading.
![{9CE096AE-7142-482f-935B-09435EDF6B9F}](https://github.com/aidenlx/obsidian-zotero-docs/assets/60467235/eb2e432f-2b4b-487d-a868-d3f1bbb73211)

**Comment by Halbert66** [comment]
The same question, where were the notes (note annotations) after md file export?

**Comment by aidenlx** [comment]
checkout latest beta version: https://zotlit.aidenlx.top/changelog/v1.1.0#v110-beta11---beta13
